#!/bin/bash
#
# s7pac v0.2 - Super Seven Performance Access Commands
#
# Created by Rick Hoppe
# Based on Timothy Hall's presentation: Gateway Performance Optimization
# See https://community.checkpoint.com/docs/DOC-3169
#
# Version History
# 0.1 First version
# 0.2 Added firewall check, send output to a logfile, page numbers of book
###############################################################################

if [[ -e /etc/profile.d/CP.sh ]]; then
    source /etc/profile.d/CP.sh
fi
if [[ -e /etc/profile.d/vsenv.sh ]]; then
    source /etc/profile.d/vsenv.sh
fi


###############################################################################
# Variables
###############################################################################
log="$HOME/s7pac_$(hostname)_$(date +%Y-%m-%d-%H%M).log"
book="Max Power: Check Point Firewall Performance Optimization - Second Edition"
book_url="http://www.maxpowerfirewalls.com/"
command1="fwaccel stat"
command2="fwaccel stats -s"
command3a="grep -c ^processor /proc/cpuinfo"
command3b="/sbin/cpuinfo"
command4="fw ctl affinity -l -r"
command5="netstat -ni"
command6="fw ctl multik stat"
command7="cpstat os -f multi_cpu -o 1 -c 5"


###############################################################################
# Function for command6 & execute before anything is printed
###############################################################################
fwctlmultikstat()
{
script -c "fw ctl multik stat" /var/tmp/core_xl_stat > /dev/null
core_stat=$(cat /var/tmp/core_xl_stat | grep -v Script)
}

fwctlmultikstat


###############################################################################
# Colors
###############################################################################
color_red=$(tput setaf 1)
color_green=$(tput setaf 2)
color_clear=$(tput sgr0)


###############################################################################
# Hello world! Inspecting environment....
###############################################################################
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Super Seven Performance Assessment Commands v0.2   (Thanks to Timothy Hall) |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Inspecting your environment: " | tee -a $log
if [[ $($CPDIR/bin/cpprod_util FwIsFirewallModule 2> /dev/null) != *"1"*  ]]; then
  printf "${color_red}NOTOK${color_clear}                                          |\n" | tee -a $log
  printf "| This script is only intended to run on a firewall (not management or VSX).  |\n" | tee -a $log
  printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
  exit 0;
else
  printf "${color_green}OK${color_clear}                                             |\n" | tee -a $log
  printf "| This is a firewall....(continuing)                                          |\n" | tee -a $log
  sleep 1
fi


###############################################################################
# Informing once about the book
###############################################################################
printf "|                                                                             |\n" | tee -a $log
printf "| Referred pagenumbers are to be found in the following book:                 |\n" | tee -a $log
printf "| $book   |\n" | tee -a $log
printf "| Available at $book_url                              |\n" | tee -a $log
printf "|                                                                             |\n"


###############################################################################
# And finally...the commands...
###############################################################################
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Command #1: $command1                                                    |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Check for : Accelerator Status must be enabled (R77.xx/R80.10 versions)     |\n" | tee -a $log
printf "|             Status must be enabled (R80.20)                                 |\n" | tee -a $log
printf "|             Accept Templates must be enabled                                |\n" | tee -a $log
printf "|             Message \"disabled\" from (low rule number) = bad                 |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 9: SecureXL throughput acceleration                                 |\n" | tee -a $log
printf "| Page 278                                                                    |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Output:                                                                     |\n" | tee -a $log
run_command1=$($command1)
echo "$run_command1" | tee -a $log
printf "\n\n" | tee -a $log

printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Command #2: $command2                                                |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Check for : Accelerated conns/Totals conns:  >25%% good, >50%% great          |\n" | tee -a $log
printf "|             Accelerated pkts/Total pkts   :  >50%% great                     |\n" | tee -a $log
printf "|             PXL pkts/Total pkts           :  >50%% OK                        |\n" | tee -a $log
printf "|             F2Fed pkts/Total pkts         :  <30%% good, <10%% great          |\n"  | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 9: SecureXL throughput acceleration                                 |\n" | tee -a $log
printf "| Page 287, Packet/Throughput Acceleration: The Three Kernel Paths            |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Output:                                                                     |\n" | tee -a $log
run_command2=$($command2)
echo "$run_command2" | tee -a $log
printf "\n\n" | tee -a $log

printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Command #3: $command3a && $command3b               |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Check for : If number of cores is roughly double what you are excpecting,   |\n" | tee -a $log
printf "|             hyperthreading may be enabled                                   |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 7: CorexL Tuning                                                    |\n" | tee -a $log
printf "| Page 239                                                                    |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Output:                                                                     |\n" | tee -a $log
run_command3a=$($command3a)
run_command3b=$($command3b)
echo "$run_command3a" | tee -a $log
echo "$run_command3b" | tee -a $log
printf "\n\n" | tee -a $log

printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Command #4: $command4                                           |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Check for : SND/IRQ/Dispatcher Cores, # of CPU's allocated to interface(s)  |\n" | tee -a $log
printf "|             Firewall Workers/INSPECT Cores, # of CPU's allocated to fw_x    |\n" | tee -a $log
printf "|             R77.30: Support processes executed on ALL CPU's                 |\n" | tee -a $log
printf "|             R80.xx: Support processes only executed on Firewall Worker Cores|\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 7: CoreXL Tuning                                                    |\n" | tee -a $log
printf "| Page 221                                                                    |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Output:                                                                     |\n" | tee -a $log
run_command4=$($command4)
echo "$run_command4" | tee -a $log
printf "\n\n" | tee -a $log

printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Command #5: $command5                                                     |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Check for : RX/TX errors                                                    |\n" | tee -a $log
printf "|             RX-DRP %% should be <0.1%% calculated by (RX-DRP/RX-OK)*100       |\n" | tee -a $log
printf "|             TX-ERR might indicate Fast Ethernet/100Mbps Duplex Mismatch     |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 2: Layers 1&2 Performance Optimization                              |\n" | tee -a $log
printf "| Page 28-35                                                                  |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 7: CoreXL Tuning                                                    |\n" | tee -a $log
printf "| Page 204                                                                    |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Output:                                                                     |\n" | tee -a $log
run_command5=$($command5)
echo "$run_command5" | tee -a $log
printf "\n\n" | tee -a $log

printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Command #6: $command6                                              |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Check for : Large # of conns on Worker 0 - IPSec VPN/VoIP?                  |\n" | tee -a $log
printf "|             Large imbalance of connections on a single or multiple Workers  |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 7: CoreXL Tuning                                                    |\n" | tee -a $log
printf "| Page 241                                                                    |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 8: CoreXL VPN Optimization                                          |\n" | tee -a $log
printf "| Page 256                                                                    |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Output:                                                                     |\n" | tee -a $log
printf "$core_stat"
printf "$core_stat" >> $log
printf "\n\n" | tee -a $log

printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Command #7: $command7                                |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Check for : High SND/IRQ Core Utilization                                   |\n" | tee -a $log
printf "|             High Firewall Worker Core Utilization                           |\n" | tee -a $log
printf "|                                                                             |\n" | tee -a $log
printf "| Chapter 7: CoreXL Tuning                                                    |\n" | tee -a $log
printf "| Page 197                                                                    |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Output:                                                                     |\n" | tee -a $log
run_command7=$($command7)
echo "$run_command7" | tee -a $log
printf "\n\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log
printf "| Thanks for using s7pac                                                      |\n" | tee -a $log
printf "+-----------------------------------------------------------------------------+\n" | tee -a $log

###############################################################################
# Cleaning up temporary files
###############################################################################
rm /var/tmp/core_xl_stat

exit 0
